---
title: "Untitled"
author: "Sreya Sudireddy"
date: "10/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## About Me
My name is Sreya Sudireddy. I am a senior at Harvard College studying Economics with a secondary in Global Health and Health Policy. 
The URL to my Github Repo is here: https://github.com/sreyasudireddy/Milestone_4


## About my Project
My project is on the effect of COVID-19 state social distancing policies on various outcomes such as positive test rate, deaths, and new administered tests. I chose this project because the pandemic is extremely relevant in the world right now and there is currently disparities in how different states have been handling social distancing policies. I got my data on state social distancing policies from the Kaiser Family Foundation (https://www.kff.org/coronavirus-covid-19/issue-brief/state-data-and-policy-actions-to-address-coronavirus/). This data is updated reguarly to reflect updated policies. I got data on COVID-19 stats from The COVID Tracking Project (https://covidtracking.com/). This data set provides various metrics on COVID-19 for every state and is also updated daily as new information comes in. For my final project, I plan on using the most updated data sets to reflect the current situation.

## Progress
So far, I was able to create graphs for the three variables (death, new positice case, new tests) I am interested in and in my app, you are able to select which state you want to see data in. On another tab, I created a data table reflective of the one on the KFF website after wrangling the data a little to remove any extra information. I also filtered out US territories, such as American Samoa and Puerto Rico, from my COVID statistics dataset to reflect the states that were in the social distancing policy data set and to keep things simple. Next time, I will create a separate Rmd file to wrangle the data to make my Shiny code cleaner. Additionally, I added buttons for the three variables that I made graphs for, however, they are currently not functional as that will be my next step to figure out. Some other things that I need to work on is that in the covid stat dataset, some numbers appear to be negative, which does not make sense, so I need to figure out what is going on there. I would also like to figure out a way to show the different data points on the graphs when you toggle over it. Additionally, rather than a table for social distancing policies, I would like to create maps to make things more visually aesthetic and easier to compare between states."


