---
title: "datawrangling"
author: "Sreya Sudireddy"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(openintro)
```

```{r}
covid_tracking <- read_csv("data/covid_12_06.csv") %>%
    filter(!state %in% c("AS", "PR", "GU", "VI", "MP")) %>%
  mutate(state = abbr2state(state))

nyt_covid <- read_csv("data/us-states_12_06.csv") %>%
    arrange(desc(date)) %>%
    filter(!fips %in% c(69, 72, 78, 66))

covid_dta <- inner_join(nyt_covid, covid_tracking, by = c("date", "state")) %>%
  select(date, state, cases, deaths, positiveIncrease, totalTestResults, totalTestResultsIncrease, positive) %>%
  mutate(positiveIncrease = replace(positiveIncrease, which(positiveIncrease < 0), 0)) %>%
  mutate(totalTestResultsIncrease = replace(totalTestResultsIncrease, which(totalTestResultsIncrease < 0), 0))

saveRDS(covid_dta, file = "coviddata.RDS")
```

```{r}
 
covid_dta %>%
  filter(state == "Massachusetts") %>%
  mutate(positiveIncrease = replace(positiveIncrease, which(positiveIncrease < 0), 0)) %>%

ggplot(aes(x = date, y = positiveIncrease)) +
    geom_line(color = "#edae49", size = 1) +
    labs(title = "COVID-19 Total Cases",
         x = "Date",
         y = "Number of Total Cases") +
  scale_y_continuous(label = scales::comma) +
  scale_x_date(date_breaks = "month", date_labels = "%b") +
    theme_classic()
```

