---
title: "Model"
author: "Sreya Sudireddy"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(naniar)
library(lubridate)
library(tidyverse)
library(janitor)
library(plm)
library(gt)
library(stargazer)
library(dplyr)
library(ggthemes)
library(leaflet)
library(broom)
```

```{r}
#Reading in covid data

covid <- readRDS("coviddata.RDS") 

# Reading in social distancing data
social_distancing_nov <- readRDS("socialdistancing_11_11.RDS")
  #replace_with_na_all(condition = ~.x == "-") %>%
 # mutate(date = "2020-11-11") %>%
  # mutate(date = as.Date(date))
  
covid_nov <- covid %>%
  slice(1:1581)

covid_oct <- covid %>%
  slice(1582:3417)

social_distancing_oct <- readRDS("socialdistancing_10_20.RDS")
 # replace_with_na_all(condition = ~.x == "-") %>%
 # mutate(date = "2020-10-20") %>%
  # mutate(date = as.Date(date))

#social_distancing_final <- bind_rows(social_distancing_nov, social_distancing_oct)

oct_dta <- full_join(covid_oct, social_distancing_oct, by = c("state" = "Location"))
nov_dta <- full_join(covid_nov, social_distancing_nov, by = c("state" = "Location"))
#merging data for model
model_dta <- bind_rows(nov_dta, oct_dta)

```


```{r}
model_dta <- model_dta %>%
  clean_names() %>%
  mutate(face_covering_requirement = case_when(face_covering_requirement == "-" ~ 0,
                                            face_covering_requirement == "Required for Certain Employees" ~ 1,
                                          face_covering_requirement == "Allows Local Officials to Require for General Public" ~ 2,
                                          face_covering_requirement == "Allows Local Officals to Require for General Public" ~ 2,
                                          face_covering_requirement == "Required for Certain Employees; Allows Local Officials to Require for General Public" ~ 2,
                                            face_covering_requirement == "Required for Certain Employees; Required for General Public" ~ 3,
                                          face_covering_requirement == "Required for General Public" ~ 3)) %>%
  mutate(face_covering_requirement = as.factor(face_covering_requirement)) %>%
  mutate(restaurant_limits = case_when(restaurant_limits == "-" ~ 0,
                                       restaurant_limits == "New Service Limits" ~ 3,
                                       restaurant_limits == "Reopened to Dine-in Service with Capacity Limits" ~ 2,
                                       restaurant_limits == "Reopened to Dine-in Service" ~ 1)) %>%
  mutate(restaurant_limits = as.factor(restaurant_limits)) %>%
  select(date, state, cases, deaths, positive_increase, total_test_results, total_test_results_increase, face_covering_requirement, restaurant_limits)

```


```{r}
model_dta <- model_dta %>%
  clean_names() %>%
  filter(state %in% c("Massachusetts", "Colorado", "New York")) %>%
  mutate(time = case_when(date >= "2020-11-06" ~ 1,
                          TRUE ~ 0)) %>%
  mutate(treated = case_when(state == "Massachusetts" ~ 1,
                             TRUE ~ 0)) %>%
  mutate(did = time * treated)

saveRDS(model_dta, file = "model.RDS")
```


```{r}
  ggplot(model_dta, aes(x = date, y = positive_increase, color = state)) +
      geom_line() +
      scale_color_manual(name = "State", 
                        labels = c("Colorado", "Massachusetts", "New York"),
                        values = c("#ef476f", "#edae49", "#219EBC")) +
      geom_vline(xintercept = as.numeric(as.Date("2020-11-05")), linetype = "dashed") +
      theme_classic() +
      labs(x = "Date", y = "Number of New Positive Cases") 

ggplot(model_dta, aes(x = date, y = total_test_results_increase, color = state)) +
  geom_line()

ggplot(model_dta, aes(x = date, y = deaths, color = state)) +
  geom_line()
```


```{r}
posincr_model <- lm(positive_increase ~ time + treated + did + state,
   data = model_dta)
summary(posincr_model)

testincr_model <- lm(total_test_results_increase ~ time + treated + did + state,
   data = model_dta)
  summary(testincr_model)

deaths_model <- lm(deaths ~ time + treated + did + state,
   data = model_dta)
  summary(deaths_model)
```


```{r}
posincr_table <- posincr_model %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high) %>%
  rename(Coefficient = estimate) %>%
  rename(`Lower End` = conf.low) %>%
  rename(`Upper End` = conf.high) %>%
  rename(`P-Value` = p.value) %>%
  filter(term %in% c("(Intercept)", "did")) %>%
  mutate(Coefficient = round(Coefficient, digits = 2)) %>%
  mutate(`P-Value` = round(`P-Value`, digits = 2)) %>%
  mutate(`Lower End` = round(`Lower End`, digits = 2)) %>%
  mutate(`Upper End` = round(`Upper End`, digits = 2))
posincr_table


testincr_table <- lm(total_test_results_increase ~ time + treated + did + state,
   data = model_dta) %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high) %>%
  rename(Coefficient = estimate) %>%
  rename(`Lower End` = conf.low) %>%
  rename(`Upper End` = conf.high) %>%
  rename(`P-Value` = p.value) %>%
  filter(term %in% c("(Intercept)", "did"))

deaths_table <- lm(deaths ~ time + treated + did + state,
   data = model_dta) %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, p.value, conf.low, conf.high) %>%
  rename(Coefficient = estimate) %>%
  rename(`Lower End` = conf.low) %>%
  rename(`Upper End` = conf.high) %>%
  rename(`P-Value` = p.value) %>%
  filter(term %in% c("(Intercept)", "did"))

```

















